---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
     - name: Display the config
      debug:
        msg: "Connected to Jenkins"